version: "3"

volumes:
  pg_data:
  web_root:
  smnrp_data:

services:
  ui:
    build:
      context: ui
    volumes:
      - ./ui/app:/app
      - "web_root:/app/dist:z"
    hostname: ui
    restart: "no"
    env_file: .env




  api:
    build:
      context: api
    hostname: api
    restart: unless-stopped
    entrypoint: sh -c '/app/entrypoint.sh'
    volumes:
      - ./api/app:/app
      - ./data:/data
      - ./api/backups:/vol/backups
      - ./api/static:/vol/web/static:z
      - ./api/media:/vol/web/media:z
    env_file: .env
    environment:
      - GIT_VERSION=${GIT_VERSION}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_LASTCOMMITDATE=${GIT_LASTCOMMITDATE}
    depends_on:
      - db


  db:
    image: postgres:15-bookworm
    hostname: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data