# Generated by Django 5.2.3 on 2025-06-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_id", models.CharField(max_length=10, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("birthyear", models.PositiveIntegerField(blank=True, null=True)),
                ("variety", models.CharField(blank=True, max_length=50, null=True)),
                ("education", models.CharField(blank=True, max_length=50, null=True)),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                ("l1", models.CharField(blank=True, max_length=50, null=True)),
                ("l2", models.CharField(blank=True, max_length=50, null=True)),
                ("l3", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                ("text_id", models.AutoField(primary_key=True, serialize=False)),
                ("text_name", models.CharField(max_length=255)),
                ("data_genre", models.CharField(blank=True, max_length=100, null=True)),
                ("text_genre", models.CharField(blank=True, max_length=100, null=True)),
                ("text_date", models.CharField(blank=True, max_length=50, null=True)),
                ("source", models.URLField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_id", models.PositiveIntegerField()),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sentences",
                        to="core.speaker",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="core.text",
                    ),
                ),
            ],
            options={
                "unique_together": {("text", "sentence_id")},
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ud_id", models.PositiveIntegerField()),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("diplomatic", models.CharField(blank=True, max_length=255, null=True)),
                ("lemma", models.CharField(blank=True, max_length=255, null=True)),
                ("ud_type_pos", models.CharField(blank=True, max_length=50, null=True)),
                ("pos_tag", models.CharField(blank=True, max_length=50, null=True)),
                ("ud_valency", models.CharField(blank=True, max_length=255, null=True)),
                ("pos_tag2", models.CharField(blank=True, max_length=50, null=True)),
                ("ud_type", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="core.sentence",
                    ),
                ),
            ],
            options={
                "unique_together": {("sentence", "ud_id")},
            },
        ),
    ]
