# Generated by Django 5.2.3 on 2025-06-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={"ordering": ["sentence", "ud_id"]},
        ),
    ]
