# Generated by Django 6.1.1 on 2026-09-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_token_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={"ordering": ["speaker_id"]},
        ),
        migrations.AlterModelOptions(
            name="text",
            options={"ordering": ["text_id"]},
        ),
        migrations.RemoveField(
            model_name="token",
            name="order",
        ),
        migrations.RemoveField(
            model_name="token",
            name="pos_tag2",
        ),
        migrations.RemoveField(
            model_name="token",
            name="ud_type_pos",
        ),
        migrations.RemoveField(
            model_name="token",
            name="ud_valency",
        ),
        migrations.AddField(
            model_name="text",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="texts", to="core.speaker"
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="source_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="text",
            name="variety",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="head_ud_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="pos_ext",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="ud_pos",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="l1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="l2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="l3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="religion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="speaker_id",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="variety",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="text",
            name="text_id",
            field=models.SlugField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["lemma"], name="core_token_lemma_2f8ad2_idx"),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["pos_tag"], name="core_token_pos_tag_e72ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["ud_type"], name="core_token_ud_type_332874_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["head_ud_id"], name="core_token_head_ud_80d1c7_idx"
            ),
        ),
    ]
