# Generated by Django 6.1.1 on 2026-09-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_speaker_options_alter_text_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="birth_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
