# Generated by Django 6.1.1 on 2026-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_speaker_birth_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speaker",
            name="education",
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="variety",
        ),
        migrations.AddField(
            model_name="speaker",
            name="dialect_region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="education_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="education_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="municipality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="place_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="source_row",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="text",
            name="source_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="text",
            name="variety_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="text",
            name="year_note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="l1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="l2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="l3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
